import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
PAYMENT_PROVIDER_TOKEN = os.getenv('PAYMENT_PROVIDER_TOKEN')

DATABASE_URL = os.getenv('DATABASE_URL')
DATABASE_FILENAME = os.getenv('DATABASE_FILENAME')

TG_VPN_SHOP_BOT_ID = int(os.getenv('TG_VPN_SHOP_BOT_ID'))

FIRST_USER_IN_DB = int(os.getenv('FIRST_USER_IN_DB'))
BASE_PRICE_IN_USDT = float(os.getenv('BASE_PRICE_IN_USDT'))
BASE_PRICE_IN_RUB = float(os.getenv('BASE_PRICE_IN_RUB'))
DISCOUNT_BASE_PROCENTS = float(os.getenv('DISCOUNT_BASE_PROCENTS'))
DISCOUNT_BASE_PROCENTS_PROMO = float(os.getenv('DISCOUNT_BASE_PROCENTS_PROMO'))

VPNSERVER_COUNTRY_NO1 = os.getenv('VPNSERVER_COUNTRY_NO1')
VPNSERVER_HTTP_NO1 = os.getenv('VPNSERVER_HTTP_NO1')
VPNSERVER_USERNAME_NO1 = os.getenv('VPNSERVER_USERNAME_NO1')
VPNSERVER_PASS_NO1 = os.getenv('VPNSERVER_PASS_NO1')
VPNSERVER_TOKEN_NO1 = os.getenv('VPNSERVER_TOKEN_NO1')
PATH_TO_CUSTOM_SERT_NO1 = os.getenv('PATH_TO_CUSTOM_SERT_NO1')
VPN_SERVER_IP_NO1 = os.getenv('VPN_SERVER_IP_NO1')

MIN_PAY = float(os.getenv('MIN_PAY'))
MIN_PAY_RUB = float(os.getenv('MIN_PAY_RUB'))

UPDATED_PRICE = BASE_PRICE_IN_USDT
UPDATED_MIN_PAY = MIN_PAY

STANDART_PARTNER_PROCENT = float(os.getenv('STANDART_PARTNER_PROCENT'))
