import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
PAYMENT_PROVIDER_TOKEN = os.getenv('PAYMENT_PROVIDER_TOKEN')

DATABASE_URL_PG = os.getenv('DATABASE_URL_PG')
DATABASE_FILENAME = os.getenv('DATABASE_FILENAME')

TG_VPN_SHOP_BOT_ID = int(os.getenv('TG_VPN_SHOP_BOT_ID'))

FIRST_USER_IN_DB = int(os.getenv('FIRST_USER_IN_DB'))
BASE_PRICE_IN_USDT = float(os.getenv('BASE_PRICE_IN_USDT'))
BASE_PRICE_IN_RUB = float(os.getenv('BASE_PRICE_IN_RUB'))
DISCOUNT_BASE_PROCENTS = float(os.getenv('DISCOUNT_BASE_PROCENTS'))
DISCOUNT_BASE_PROCENTS_PROMO = float(os.getenv('DISCOUNT_BASE_PROCENTS_PROMO'))

VPNSERVER_COUNTRY_NO1 = os.getenv('VPNSERVER_COUNTRY_NO1')
VPNSERVER_HTTP_NO1 = os.getenv('VPNSERVER_HTTP_NO1')
VPNSERVER_USERNAME_NO1 = os.getenv('VPNSERVER_USERNAME_NO1')
VPNSERVER_PASS_NO1 = os.getenv('VPNSERVER_PASS_NO1')
VPNSERVER_TOKEN_NO1 = os.getenv('VPNSERVER_TOKEN_NO1')
PATH_TO_CUSTOM_SERT_NO1 = os.getenv('PATH_TO_CUSTOM_SERT_NO1')
VPN_SERVER_IP_NO1 = os.getenv('VPN_SERVER_IP_NO1')

MIN_PAY = float(os.getenv('MIN_PAY'))
MIN_PAY_RUB = float(os.getenv('MIN_PAY_RUB'))

UPDATED_PRICE = BASE_PRICE_IN_USDT
UPDATED_MIN_PAY = MIN_PAY

STANDART_PARTNER_PROCENT = float(os.getenv('STANDART_PARTNER_PROCENT'))


BOT_SHOP_NAME = os.getenv('BOT_SHOP_NAME')
BOT_TOP_IMAGE = os.getenv('BOT_TOP_IMAGE')

SERVER_COUNTRY_1 = os.getenv('SERVER_COUNTRY_1')
SERVER_COUNTRY_2 = os.getenv('SERVER_COUNTRY_2')
SERVER_COUNTRY_3 = os.getenv('SERVER_COUNTRY_3')
SERVER_COUNTRY_4 = os.getenv('SERVER_COUNTRY_4')
SERVER_COUNTRY_5 = os.getenv('SERVER_COUNTRY_5')

SERVER_COUNTRY_ID_1 = int(os.getenv('SERVER_COUNTRY_ID_1'))
SERVER_COUNTRY_ID_2 = int(os.getenv('SERVER_COUNTRY_ID_2'))
SERVER_COUNTRY_ID_3 = int(os.getenv('SERVER_COUNTRY_ID_3'))
SERVER_COUNTRY_ID_4 = int(os.getenv('SERVER_COUNTRY_ID_4'))
SERVER_COUNTRY_ID_5 = int(os.getenv('SERVER_COUNTRY_ID_5'))


MESSTOADM = 1
CHOOSEUSER = 2
TYPEUSERID = 3
CHOOSESERVER = 4
CHOOSEUSERBLO = 5
TYPEMESSALL = 6
GETINFO = 7
BLOCKID = 8
PLUSDAYSID = 9
PLUSDAYSDAYS = 10
PLUSDAYSSUB = 11
ADDPARTID = 12
ADDPARTPRC = 13
ADDPARTHTTP = 14
ADDPARTWLT = 15
PAYPARTID = 16
PAYPARTSUM = 17
UNBLOCKID = 18


# Base directory of the project
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Assets folder
ASSETS_DIR = os.path.join(BASE_DIR, "assets")

ADMINS_LIST = []
ADMINS_LIST.append(FIRST_USER_IN_DB)